services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
      # - "9443:9443"
    restart: "no"

  wiremock: # <Wiremock baseUrl>/__admin/webapp
    image: "holomekc/wiremock-gui:latest"
    container_name: wiremock
    ports:
      - "8080:8080"
    command: "--port 8080 --verbose --max-request-journal 1000 --enable-stub-cors --local-response-templating"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings # Маппинги
      - ./wiremock/__files:/home/wiremock/__files # Файлы ответов
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: "no"

volumes:
  postgresql:
  postgresql_data:
  portainer_data:
